
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 37;
  public static final int DIVIDE = 8;
  public static final int INTEGER = 14;
  public static final int L_ROUND = 10;
  public static final int SEMI = 2;
  public static final int R_ROUND = 11;
  public static final int MINUS = 6;
  public static final int CHARACTER = 16;
  public static final int RATIONAL = 17;
  public static final int IN = 24;
  public static final int FI = 32;
  public static final int TYPEDEF = 29;
  public static final int PLUS = 5;
  public static final int MAIN = 22;
  public static final int IF = 31;
  public static final int ELSE_IF = 34;
  public static final int CARET = 9;
  public static final int ID = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 15;
  public static final int OD = 39;
  public static final int RETURN = 28;
  public static final int DICTIONARY = 19;
  public static final int error = 1;
  public static final int L_CURLY = 12;
  public static final int R_CURLY = 13;
  public static final int EQEQ = 4;
  public static final int NUMBER = 41;
  public static final int FUNCTION_DEF = 30;
  public static final int VOID = 21;
  public static final int EQ = 3;
  public static final int TIMES = 7;
  public static final int ELSE = 35;
  public static final int READ = 26;
  public static final int WHILE = 36;
  public static final int FLOAT = 18;
  public static final int THEN = 33;
  public static final int LEN = 23;
  public static final int ALIAS = 25;
  public static final int SEQUENCE = 20;
  public static final int DO = 38;
  public static final int PRINT = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "EQ",
  "EQEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "CARET",
  "L_ROUND",
  "R_ROUND",
  "L_CURLY",
  "R_CURLY",
  "INTEGER",
  "BOOLEAN",
  "CHARACTER",
  "RATIONAL",
  "FLOAT",
  "DICTIONARY",
  "SEQUENCE",
  "VOID",
  "MAIN",
  "LEN",
  "IN",
  "ALIAS",
  "READ",
  "PRINT",
  "RETURN",
  "TYPEDEF",
  "FUNCTION_DEF",
  "IF",
  "FI",
  "THEN",
  "ELSE_IF",
  "ELSE",
  "WHILE",
  "FORALL",
  "DO",
  "OD",
  "ID",
  "NUMBER"
  };
}

