
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 44;
  public static final int SEQ = 26;
  public static final int DIVIDE = 8;
  public static final int INTEGER = 20;
  public static final int L_ROUND = 12;
  public static final int R_SQUARE = 19;
  public static final int SEMI = 2;
  public static final int R_ROUND = 13;
  public static final int MINUS = 6;
  public static final int CHARACTER = 22;
  public static final int RATIONAL = 23;
  public static final int IN = 31;
  public static final int COMMA = 11;
  public static final int FI = 39;
  public static final int TYPEDEF = 36;
  public static final int PLUS = 5;
  public static final int ELSE_IF = 41;
  public static final int IF = 38;
  public static final int MAIN = 29;
  public static final int CARET = 9;
  public static final int ID = 48;
  public static final int EOF = 0;
  public static final int BOOLEAN = 21;
  public static final int OD = 46;
  public static final int RETURN = 35;
  public static final int error = 1;
  public static final int L_CURLY = 14;
  public static final int R_CURLY = 15;
  public static final int EQEQ = 4;
  public static final int NUMBER = 49;
  public static final int FUNCTION_DEF = 37;
  public static final int VOID = 27;
  public static final int EQ = 3;
  public static final int TOP = 28;
  public static final int TIMES = 7;
  public static final int L_ANGLE = 16;
  public static final int COLON = 10;
  public static final int ELSE = 42;
  public static final int DICT = 25;
  public static final int R_ANGLE = 17;
  public static final int L_SQUARE = 18;
  public static final int READ = 33;
  public static final int WHILE = 43;
  public static final int FLOAT = 24;
  public static final int THEN = 40;
  public static final int LEN = 30;
  public static final int ALIAS = 32;
  public static final int DO = 45;
  public static final int PRINT = 34;
  public static final int IDENTIFIER = 47;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "EQ",
  "EQEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "CARET",
  "COLON",
  "COMMA",
  "L_ROUND",
  "R_ROUND",
  "L_CURLY",
  "R_CURLY",
  "L_ANGLE",
  "R_ANGLE",
  "L_SQUARE",
  "R_SQUARE",
  "INTEGER",
  "BOOLEAN",
  "CHARACTER",
  "RATIONAL",
  "FLOAT",
  "DICT",
  "SEQ",
  "VOID",
  "TOP",
  "MAIN",
  "LEN",
  "IN",
  "ALIAS",
  "READ",
  "PRINT",
  "RETURN",
  "TYPEDEF",
  "FUNCTION_DEF",
  "IF",
  "FI",
  "THEN",
  "ELSE_IF",
  "ELSE",
  "WHILE",
  "FORALL",
  "DO",
  "OD",
  "IDENTIFIER",
  "ID",
  "NUMBER"
  };
}

